// ── BOOKMARKS / LAST POSITION ─────────────────────────────────────────────────
// Persists and restores the user's reading position (chapter index + scroll Y)
// in IndexedDB. Called by openSearch(), openLibrary(), and other functions
// that navigate away from a chapter, so the user can return to where they were.
//
// The IDB key used is:  `${studyId}_lastPosition`  in the answers store.
//
// Dependencies (all available as globals before this file loads):
//   currentChapter, isNonChapterPage – state.js
//   StudyIDB                         – idb.js
//   goToChapter                      – navigation.js (runtime only)

// Saves the current chapter index and scroll position to IDB.
// Guarded by isNonChapterPage so positions on settings/progress pages are not saved.
// Fire-and-forget async: callers do not need to await.
function saveLastPosition() {
  if (isNonChapterPage) return;
  const studyId = window.activeStudyId;
  if (!studyId) return;
  const pos = {
    chapterIdx: currentChapter,
    scrollY: window.scrollY
  };
  // Keep the sync cache up to date so renderTitlePage() sees the latest position.
  window.lastPositionCache = pos;
  // Fire-and-forget — position loss on failure is acceptable.
  StudyIDB.setAnswerRaw(`${studyId}_lastPosition`, JSON.stringify(pos))
    .catch(e => console.warn('[saveLastPosition] IDB write failed.', e));
}

// Removes the saved position for the current study from IDB.
// Called after clearing all answers, since the position would point into a
// now-empty chapter and cause a confusing restore on next launch.
// Fire-and-forget async.
function clearLastPosition() {
  const studyId = window.activeStudyId;
  if (!studyId) return;
  window.lastPositionCache = null;
  StudyIDB.deleteAnswerRaw(`${studyId}_lastPosition`)
    .catch(e => console.warn('[clearLastPosition] IDB delete failed.', e));
}

// Retrieves the saved position object ({ chapterIdx, scrollY }) for the current study.
// Returns a Promise resolving to the position object, or null if none exists or
// if the stored JSON is malformed.
async function getLastPosition() {
  const studyId = window.activeStudyId;
  if (!studyId) return null;
  try {
    const raw = await StudyIDB.getAnswerRaw(`${studyId}_lastPosition`);
    return raw ? JSON.parse(raw) : null;
  } catch (e) {
    return null;
  }
}

// Navigates to the last saved chapter and restores the scroll position.
async function returnToLastPosition() {
  const pos = await getLastPosition();
  if (!pos) return;
  await Router.navigate({ page: 'chapter', idx: pos.chapterIdx, scrollY: pos.scrollY });
  window.scrollTo(0, pos.scrollY);
}

// ── SAFE LOCALSTORAGE WRITE ───────────────────────────────────────────────────
// safeSetItem is retained for any remaining localStorage writes (app settings,
// study registry, onboarding flags, etc. — the non-answer data that intentionally
// stays in localStorage). Answer data now goes through StudyIDB directly.
//
// Exposed on window so inline onchange handlers in HTML strings (e.g. the Likert
// radio generated by renderLikertScale in modals.js) can call it directly.
function safeSetItem(key, value) {
  try {
    localStorage.setItem(key, value);
  } catch (e) {
    console.warn('[safeSetItem] localStorage write failed for key:', key, e);
  }
}
window.safeSetItem = safeSetItem;

// ── TOAST ─────────────────────────────────────────────────────────────────────
// Escapes a string for safe injection into innerHTML.
// Covers the four characters that are meaningful in HTML contexts.
// Use this wherever user-supplied or study-supplied strings are injected via
// isHtml: true in showToast(), or any other innerHTML assignment.
function escapeHtml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/'/g, '&#39;')
    .replace(/"/g, '&quot;');
}

/**
 * showToast(options)
 *
 * options:
 *   message    {string}  – text or HTML to display. Default: current toast text (no change).
 *   isHtml     {boolean} – if true, sets innerHTML instead of textContent. Default: false.
 *   isManual   {boolean} – if false, only shows when appSettings.autoSaveToast is on. Default: false.
 *   duration   {number}  – display time in ms. Default: auto-calculated from message length.
 *   elementId  {string}  – ID of the toast element to use. Default: 'toast'.
 *   resetText  {string}  – text to restore after hiding. Default: '✓ Answers saved'.
 */
function showToast({
  message    = null,
  isHtml     = false,
  isManual   = false,
  duration   = null,
  elementId  = 'toast',
  resetText  = t('utils_answers_saved')
} = {}) {
  if (!isManual && !appSettings.autoSaveToast) return;

  const toast = document.getElementById(elementId);
  if (!toast) return;

  if (message !== null) {
    if (isHtml) toast.innerHTML = message;
    else        toast.textContent = message;
  }

  const text     = toast.textContent;
  const auto     = Math.min(3500 + Math.max(0, text.length - 30) * 20, 10000);
  const ms       = duration ?? auto;

  toast.classList.add('show');
  setTimeout(() => {
    toast.classList.remove('show');
    if (message !== null) {
      setTimeout(() => { toast.textContent = resetText; }, 300);
    }
  }, ms);
}

// Shows the chapter-completion celebration toast the first time a chapter
// reaches 100% completion. The "celebrated" flag is stored as a standalone
// IDB key (${studyId}_celebrated_ch${N}) so it is never touched by the
// saveAnswers() read-modify-write cycle on the chapter record, eliminating
// the race condition where a concurrent save could overwrite the flag.
//
// Uses getAnswerRaw/setAnswerRaw (no read-modify-write needed — the key holds
// only the flag value). Fire-and-forget from updateProgress().
async function showCelebrationToast(ch) {
  const studyId = window.activeStudyId;
  if (!studyId) return;

  const flagKey = celebratedIDBKey(studyId, ch.chapterNumber);

  // Already celebrated this chapter — don't show again.
  let existing;
  try {
    existing = await StudyIDB.getAnswerRaw(flagKey);
  } catch (e) {
    console.warn('[showCelebrationToast] IDB read failed.', e);
    return;
  }
  if (existing) return;

  // Write the flag before showing the toast so a rapid double-trigger
  // (e.g. two quick saves to 100%) doesn't show it twice.
  try {
    await StudyIDB.setAnswerRaw(flagKey, '1');
  } catch (e) {
    console.warn('[showCelebrationToast] IDB write failed.', e);
    return;
  }


  showToast({
    message:   `⭐ ${escapeHtml(ch.chapterTitle)} ⭐<br><span class="celebration-toast-sub">${t('utils_celebration_sub', { number: ch.chapterNumber })}</span><br><button class="celebration-toast-share" onclick="shareAnswers(); document.getElementById('celebrationToast').classList.remove('show')">${t('utils_celebration_share')} ${ICONS.share}</button>`,
    isHtml:    true,
    isManual:  true,
    duration:  10000,
    elementId: 'celebrationToast',
    resetText: ''   // celebration toast has no default text to restore
  });
}

// ── LONG PRESS TO COPY ANSWER ─────────────────────────────────────────────────
// Detects a long press (600ms hold) on any answer field and copies its text to
// the clipboard, with brief visual feedback. Works alongside normal tap/scroll
// behaviour: touchmove cancels the timer so scrolling never triggers a copy.
//
// Dependencies: none (uses only DOM APIs and showCopyFeedback / copyToClipboard defined below).

// Timer handle for the long-press detection.
let longPressTimer = null;
// Duration (ms) the user must hold before the copy action fires.
const LONG_PRESS_DURATION = 600; // ms

// Attaches touchstart / touchend / touchmove listeners to the document.
// Call once from the startup block — it listens on every answer field via
// event delegation (no need to re-attach when new fields are rendered).
function initLongPressCopy() {
  document.addEventListener('touchstart', e => {
    const field = e.target.closest('.answer-field');
    if (!field) return;
    longPressTimer = setTimeout(() => {
      const text = field.value.trim();
      if (!text) return;
      copyToClipboard(text);
      showCopyFeedback(field);
    }, LONG_PRESS_DURATION);
  }, { passive: true });

  function clearLongPressTimer() {
    clearTimeout(longPressTimer);
    longPressTimer = null;
  }

  document.addEventListener('touchend',    clearLongPressTimer);
  document.addEventListener('touchmove',   clearLongPressTimer);
  document.addEventListener('touchcancel', clearLongPressTimer);
}

// Copies text to the clipboard using the modern Clipboard API where available,
// falling back to the legacy execCommand approach via fallbackCopy().
function copyToClipboard(text) {
  if (navigator.clipboard && navigator.clipboard.writeText) {
    navigator.clipboard.writeText(text).catch(() => fallbackCopy(text));
  } else {
    fallbackCopy(text);
  }
}

// Legacy clipboard copy using a temporarily appended off-screen textarea.
// Used when navigator.clipboard is unavailable (e.g. non-HTTPS or older Android WebViews).
// NOTE: document.execCommand('copy') is deprecated but remains the most reliable
// fallback across older Android WebViews. Replace with navigator.clipboard
// everywhere once minimum WebView version supports it.
function fallbackCopy(text) {
  const el = document.createElement('textarea');
  el.value = text;
  el.style.cssText = 'position:fixed; top:-9999px; left:-9999px;';
  document.body.appendChild(el);
  el.select();
  document.execCommand('copy');
  document.body.removeChild(el);
}

// Provides visual feedback after a long-press copy: briefly turns the field
// border green and shows "✓ Answer copied" in the toast, then restores both.
function showCopyFeedback(field) {
  const original = field.style.borderColor;
  field.style.transition = 'border-color 0.1s';
  field.style.borderColor = 'var(--success)';
  setTimeout(() => { field.style.borderColor = original; }, 1200);

  Swal.fire({
    toast: true,
    position: 'bottom',
    icon: 'success',
    title: t('utils_answer_copied'),
    showConfirmButton: false,
    timer: 3000,
    timerProgressBar: true,
  });
}

// ── PLATFORM DETECTION ────────────────────────────────────────────────────────
// Returns the platform the app is running on.
// 'android' — wrapped in the Android WebView (window.Android bridge present)
// 'ios'     — running on iOS Safari/WebView (reserved for future native wrapper)
// 'web'     — all other browsers / desktop
//
// Use this instead of raw window.Android checks so platform logic is consistent
// and easy to extend when iOS ships.
function getPlatform() {
  if (window.Android) return 'android';
  if (/iP(hone|ad|od)/.test(navigator.userAgent)) return 'ios';
  return 'web';
}
